apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
      name: hello
    spec:
      containers:
        - image: spinnakerkube.azurecr.io/spinnaker:${ parameters['parentExecution']['parameters']['Pre-PRODImageTAG'] }
          name: hello
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  ports:
    - name: testport
      port: 80
      targetPort: 8000
  selector:
    app: hello
  type: LoadBalancer
