<<<<<<< HEAD
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helloworld-chart.serviceAccountName" . }}
  labels:
{{ include "helloworld-chart.labels" . | nindent 4 }}
{{- end -}}
=======
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helloworld-chart.serviceAccountName" . }}
  labels:
{{ include "helloworld-chart.labels" . | nindent 4 }}
{{- end -}}
>>>>>>> a8ed571f2f6f15e10e926b3ba82cf94a280e5c73
