<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld-chart.fullname" . }}
  labels:
    {{- include "helloworld-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helloworld-chart.selectorLabels" . | nindent 4 }}
=======
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld-chart.fullname" . }}
  labels:
    {{- include "helloworld-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helloworld-chart.selectorLabels" . | nindent 4 }}
>>>>>>> a8ed571f2f6f15e10e926b3ba82cf94a280e5c73
